# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        Web\AppBundle\Entity\User:
            algorithm: sha256
            encode_as_base64: false
            iterations: 1

    providers:
       users_provider:
           id: funglobe_user_provider

    role_hierarchy:
        ROLE_MEMBER:           [ROLE_MEMBER]
        ROLE_MODERATOR:        [ROLE_MEMBER, ROLE_MODERATOR]
        ROLE_ADMIN:            [ROLE_MODERATOR, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - funglobe_authenticator
            logout:
                path: main_logout
                target: main_login
                handlers: [logout_listener]
            remember_me:
                secret:   '%secret%'
                name: appfgewebckus
                lifetime: 604800
                path:     /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/admin/home, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/profile, role: ROLE_MEMBER }
        - { path: ^/[^/]+/admin, roles: [ROLE_MODERATOR, ROLE_ADMIN] }
